services:
  - type: worker
    name: revampbot
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python enhanced-revampbot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: BOT_PREFIX
        value: "!"
      - key: DATABASE_PATH
        value: revampbot.db
      - key: LOG_LEVEL
        value: INFO
